name: "Generate Report"
on:
  schedule:
  - cron: "0 0 1 * *"  # at 00:00 on 1st day of every month

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SYNAPSE_USERNAME: "synapse-reports"
      NOTIFICATION_PRINCIPAL_ID: "3386552"
      TABLE_SYNAPSE_ID: "syn18406644"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas synapseclient

      - name: Generate Storage Report
        run: |
          python GenerateAndSendStorageReport.py -e ${{env.SYNAPSE_USERNAME}} -k ${{secrets.SYNAPSE_API_KEY}} -r ${{env.NOTIFICATION_PRINCIPAL_ID}} -t ${{env.TABLE_SYNAPSE_ID}}

      # prevent GH action from disabling scheduled builds
      - uses: gautamkrishnar/keepalive-workflow@master
